app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


class Movie:
    '''
    Movie class to define Movie Objects
    '''

    def __init__(self,id,title,overview,poster,vote_average,vote_count, trailer):
        self.id =id
        self.title = title
        self.overview = overview
        self.poster = 'https://image.tmdb.org/t/p/w500/'+ poster
        self.vote_average = vote_average
        self.vote_count = vote_count
        self.trailer = trailer


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def __repr__(self):
        return f'User {self.username}'


class Genres(db.Model):
    __tablename__='genres'
    id=db.Column(db.Integer,primary_key = True)
    name= db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, name):
        self.name = name

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField
from wtforms.validators import Required

class GenreForm(FlaskForm):
    name = StringField('Add a Genre', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from config import *
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail, Message


db=SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    from .request import configure_request
    configure_request(app)

    # auth
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from app import mail
from . import main
from ..request import get_movies, get_movie
from ..models import *
from flask_login import login_required
from flask_mail import Mail, Message
from .forms import *
from .. import db
import http.client
import requests, json
from ..models import *


@main.route('/')
@login_required
def index():

    '''
    View root page function that returns the index page and movie list
    '''

    # Getting popular movies
    popular_movies = get_movies('popular')
    upcoming_movie = get_movies('upcoming')
    now_showing_movie = get_movies('now_playing')

    title = 'Home - Welcome to The best Movie Review Website Online'
    return render_template('index.html', title=title, popular=popular_movies, upcoming=upcoming_movie,
                           now_showing=now_showing_movie)


@main.route('/movie/<int:id>')
@login_required
def movie(id):

    '''
    View movie page function that returns the movie details page and its data
    '''
    movie = get_movie(id)
    title = f'{movie.title}'
    return render_template('movie.html',title = title,movie = movie)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    mygenres= Genres.query.all()

    url=("http://api.themoviedb.org/3/genre/movie/list?language=en-US&api_key=63fcd85379cd2a0aaeed015f96dcddf2")
    response=requests.get(url).json()
    x = list(response['genres'])
    genres=[]
    for i in x:
        genre=(i['name'])
        genres.append(genre)
    print(genres)
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user, genres= genres, mygenres=mygenres)


@main.route('/user/<uname>/genre/new/', methods = ['GET','POST'])
def new_genre(uname):
    form = GenreForm()
    user = User.query.filter_by(username = uname).first()

    if form.validate_on_submit():
        genre = form.name.data
        new_genre = Genres(genre)
        db.session.add(new_genre)
        db.session.commit()
        if user.is_authenticated:
            return redirect(url_for('main.profile',uname=uname))

    title = 'Add a genre'
    return render_template('new_genre.html',title = title, genre_form=form, user = user)

app/templates/base.html
<html>
<head>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="w3-bar w3-black w3-hide-small">
    {% if current_user.is_authenticated %}
  <a href="{{url_for('main.profile',uname=current_user.username)}}" class="w3-bar-item w3-button w3-padding"> My Subscriptions </i></a>
  <a href="{{url_for('auth.logout')}}" class="w3-bar-item w3-button w3-right w3-padding"> Logout </i></a>
    {% else %}
  <a href="{{url_for('auth.login')}}" class="w3-bar-item w3-button"><i class="fa fa-login w3-padding"> Login </i></a>
     {%endif%}
</div>
{% block content%}

{%endblock%}
</body>
</html>

app/templates/fourOwfour.html
{%extends 'base.html'%}
{% block content%}
<div class="w3-display-middle">
    <br><br><br><br><br><br><br>
<h4 style="text-align:center">WHOOOPS!!! we can't find that page</h4>
</div>
{%endblock%}
</body>
</html>

app/templates/index.html
<html>
<head>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="w3-bar w3-black w3-hide-small">
    {% if current_user.is_authenticated %}
  <a href="{{url_for('main.profile',uname=current_user.username)}}" class="w3-bar-item w3-button w3-padding"> My Subscriptions </i></a>
  <a href="{{url_for('auth.logout')}}" class="w3-bar-item w3-button w3-right w3-padding"> Logout </i></a>
    {% else %}
  <a href="{{url_for('auth.login')}}" class="w3-bar-item w3-button"><i class="fa fa-snapchat"> Login </i></a>
     {%endif%}
</div>
        <div class="w3-center"><h4 style="text-align:center">Movie of the Day</h4>
            <h5 class="w3-center"> <em>Some Popular Movies</em></h5>
<div class="w3-row-padding">
    {% for popular_movie in popular %}
        <div class="w3-col s2 w3-margin-top w3-center ">
        <img src="{{ popular_movie.poster }}" class="w3-card-4" alt="poster"style="width:100%">
        <div class="w3-container w3-center">
        <p>{{ popular_movie.title | capitalize}}</p>
        </div>
        </div>
    {% endfor %}
</div>




 </body>
</html>

app/templates/new_genre.html
{% extends 'bootstrap/base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-10">
    <br><br><br><br></div><br><br><br><br><br><br><div class="w3-center"><h4 style="text-align:center"> <em>Movie of the Day</em> - Add a Genre</h4><br><br><br><br><br><br>

{{wtf.quick_form(genre_form)}}

</div>
</div>
</div>

{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4 w3-center">
    <h4>Movie of the Day</h4>
    <h5> <em>{{user.username| capitalize}}'s Subscriptions</em> </h5>
    <br>
    <a href="{{url_for('main.new_genre',uname=current_user.username)}}" class="w3-black w3-button w3-round"><strong>+</strong> a genre</a>
  </div>

  <!--Display subscriptions-->
  <div class="w3-row w3-margin">
  <ul class="w3-ul w3-border w3-col w3-hoverable w3-half w3-left">
    <li class="w3-black w3-center">Available Genres</li>
   {%for genre in genres%}
    <li class="w3-text-black">{{genre | capitalize}}</li>
    {%endfor%}
  </ul>

    <ul class="w3-ul w3-border w3-hoverable w3-half w3-right">
    <li class="w3-black w3-center">My Genres</li>
        {%for genre in mygenres%}
    <li class="w3-text-black">{{genre.name | capitalize}}</li>
    {%endfor%}
  </ul>
    </ul>
    </div>

</div>
</div>
{% endblock %}